### ISSUE TITLE
what missing here?

### ISSUE THREAD

**Issue by johnfelipe** [t-shah02/virtuagnosis#1]
root@felipe:~/virtuagnosis/backend# export FLASK_ENV=development
	root@felipe:~/virtuagnosis/backend# flask run
	 * Serving Flask app 'server.py' (lazy loading)
	 * Environment: development
	 * Debug mode: on
	Traceback (most recent call last):
	  File "/usr/local/bin/flask", line 8, in <module>
		sys.exit(main())
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 994, in main
		cli.main(args=sys.argv[1:])
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 600, in main
		return super().main(*args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
		return __callback(*args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 84, in new_func
		return ctx.invoke(f, obj, *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
		return __callback(*args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 849, in run_command
		app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 324, in __init__
		self._load_unlocked()
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 350, in _load_unlocked
		self._app = rv = self.loader()
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 406, in load_app
		app = locate_app(self, import_name, name)
	  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 260, in locate_app
		__import__(module_name)
	  File "/root/virtuagnosis/backend/server.py", line 2, in <module>
		from disease_predictor import find_closest_diseases
	  File "/root/virtuagnosis/backend/disease_predictor.py", line 6, in <module>
		df = pd.read_csv("backend/final_disease_data.csv")
	  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
		return func(*args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 680, in read_csv
		return _read(filepath_or_buffer, kwds)
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 575, in _read
		parser = TextFileReader(filepath_or_buffer, **kwds)
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 933, in __init__
		self._engine = self._make_engine(f, self.engine)
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
		self.handles = get_handle(  # type: ignore[call-overload]
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 789, in get_handle
		handle = open(
	FileNotFoundError: [Errno 2] No such file or directory: 'backend/final_disease_data.csv'

**Comment by johnfelipe** [comment]
anyone?
